# Generated by Django 5.2.8 on 2025-11-08 14:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(db_index=True, default=1, help_text='Tenant/Restaurant ID untuk multi-tenancy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('offline_customer_name', models.CharField(blank=True, help_text='Nama customer untuk offline tanpa registrasi', max_length=200)),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKEAWAY', 'Takeaway'), ('DELIVERY', 'Delivery')], max_length=20)),
                ('order_channel', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=10)),
                ('table_number', models.CharField(blank=True, help_text='Nomor meja (untuk Dine In)', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal_currency', models.CharField(choices=[('IDR', 'Indonesian Rupiah'), ('EGP', 'Egyptian Pound')], default='IDR', max_length=3)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_currency', models.CharField(choices=[('IDR', 'Indonesian Rupiah'), ('EGP', 'Egyptian Pound')], default='IDR', max_length=3)),
                ('delivery_address', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Link ke customer (null untuk offline walk-in)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(db_index=True, default=1, help_text='Tenant/Restaurant ID untuk multi-tenancy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_amount', models.DecimalField(decimal_places=2, help_text='Harga saat order dibuat (snapshot)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_currency', models.CharField(choices=[('IDR', 'Indonesian Rupiah'), ('EGP', 'Egyptian Pound')], default='IDR', max_length=3)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal_currency', models.CharField(choices=[('IDR', 'Indonesian Rupiah'), ('EGP', 'Egyptian Pound')], default='IDR', max_length=3)),
                ('notes', models.TextField(blank=True, help_text="Special request (e.g., 'extra spicy', 'no onion')")),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(db_index=True, default=1, help_text='Tenant/Restaurant ID untuk multi-tenancy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User yang update status', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(db_index=True, default=1, help_text='Tenant/Restaurant ID untuk multi-tenancy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_spent_currency', models.CharField(default='IDR', max_length=3)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='customers.customer')),
                ('favorite_category', models.ForeignKey(blank=True, help_text='Kategori yang paling sering dipesan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category')),
            ],
            options={
                'verbose_name_plural': 'Customer Analytics',
                'indexes': [models.Index(fields=['total_spent_amount'], name='orders_cust_total_s_70c6b9_idx'), models.Index(fields=['total_orders'], name='orders_cust_total_o_60d7e2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'order_channel'], name='orders_orde_order_t_2ade18_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='orders_orde_custome_59b6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimeline',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_a5a9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimeline',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_e6b870_idx'),
        ),
    ]
