# Generated by Django 5.2.8 on 2025-11-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(db_index=True, default=1, help_text='Tenant/Restaurant ID untuk multi-tenancy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, max_length=50)),
                ('order_type', models.CharField(max_length=20)),
                ('order_channel', models.CharField(max_length=10)),
                ('menu_item_id', models.IntegerField(db_index=True)),
                ('menu_item_name', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_currency', models.CharField(default='IDR', max_length=3)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('completed_at', models.DateTimeField(db_index=True)),
                ('completed_date', models.DateField(db_index=True)),
                ('completed_year_month', models.CharField(db_index=True, max_length=7)),
                ('completed_year', models.IntegerField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Menu Order Logs',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['menu_item_id', 'completed_year_month'], name='orders_menu_menu_it_a8e1a0_idx'), models.Index(fields=['completed_date'], name='orders_menu_complet_d66f08_idx'), models.Index(fields=['category_name', 'completed_year_month'], name='orders_menu_categor_d18cf8_idx')],
            },
        ),
    ]
