# Generated by Django 5.2.8 on 2025-11-08 14:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(db_index=True, default=1, help_text='Tenant/Restaurant ID untuk multi-tenancy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0, help_text='Urutan tampilan (angka kecil tampil lebih dulu)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['restaurant_id', 'is_active'], name='menu_catego_restaur_c97a7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(db_index=True, default=1, help_text='Tenant/Restaurant ID untuk multi-tenancy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_currency', models.CharField(choices=[('IDR', 'Indonesian Rupiah'), ('EGP', 'Egyptian Pound')], default='IDR', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/%Y/%m/')),
                ('stock_quantity', models.IntegerField(default=0, help_text='Stok tersedia (update manual setiap hari)', validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_unit', models.CharField(choices=[('portion', 'Portion'), ('piece', 'Piece'), ('kg', 'Kilogram'), ('liter', 'Liter')], default='portion', max_length=20)),
                ('is_unlimited_stock', models.BooleanField(default=False, help_text='Centang jika stok unlimited (tidak perlu tracking)')),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Alert jika stok dibawah angka ini', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True, help_text='Tersedia untuk order (auto false jika stok habis)')),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0, help_text='Urutan tampilan dalam kategori')),
                ('preparation_time', models.IntegerField(default=15, help_text='Waktu persiapan (menit)', validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
            ],
            options={
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category', 'display_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_available'], name='menu_menuit_categor_ed897a_idx'), models.Index(fields=['is_best_seller'], name='menu_menuit_is_best_7703ed_idx'), models.Index(fields=['price_currency'], name='menu_menuit_price_c_1e24c7_idx'), models.Index(fields=['stock_quantity'], name='menu_menuit_stock_q_d8049f_idx')],
            },
        ),
    ]
