# Generated by Django 5.2.8 on 2025-11-08 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock_reserved',
            field=models.IntegerField(default=0, help_text='Stok yang direserve untuk pending orders', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
