# Generated by Django 5.2.8 on 2025-11-08 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(db_index=True, default=1, help_text='Tenant/Restaurant ID untuk multi-tenancy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, help_text='Nomor telepon (unique identifier)', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('customer_type', models.CharField(choices=[('GUEST', 'Guest Customer'), ('MEMBER', 'Member Customer')], default='GUEST', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, help_text='Link ke Django User (untuk member yang bisa login)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='customers_c_phone_n_cabfe1_idx'), models.Index(fields=['customer_type'], name='customers_c_custome_47da94_idx')],
            },
        ),
    ]
